name: notification test

on:
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Fazer checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Build da imagem Docker
    - name: Build Docker Image
      run: |
        docker build -t notification-app .

    # 3. Executar a aplicação no container
    - name: Run Docker Container
      run: |
        docker run -d -p 3000:3000 --name notification-app notification-app

    # 4. Testar o endpoint
    - name: Test endpoint
      run: |
        sleep 5 # Aguarda o container iniciar
        curl http://localhost:3000/notification/health

    # 5. Remover o container após os testes
    - name: Clean up
      run: |
        docker stop notification-app
        docker rm notification-app
