name: notification test

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checar o código
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar o Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  

# 3. Instalar dependências
- name: Install dependencies
  working-directory: ../../notification  
  run: npm install

# 4. Rodar os testes
- name: Run tests
  working-directory: ../../notification 
  run: npm start
