name: notification test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t notification-app -f ./notification/Dockerfile ./notification

    - name: Run Docker Container
      run: |
        docker run -d -p 3000:3000 --name notification-app notification-app

    - name: Verify Docker Container
      run: docker ps -a

    - name: Inspect Docker Logs
      run: docker logs notification-app

    - name: Test endpoint
      run: |
        for i in {1..15}; do
          if curl -s http://localhost:3000/notification/health; then
            echo "Service is up!"
            exit 0
          fi
          echo "Service not ready. Retrying in 3 seconds..."
          sleep 3
        done
        echo "Service did not start in time."
        exit 1

    - name: Clean up
      run: |
        docker stop notification-app
        docker rm notification-app
