name: Testing dummy service

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Executar os testes
      - name: Run tests
        run: npm test

      # Build da imagem Docker
      - name: Build Docker image
        run: docker build -t dummy-service .

      # Testar o contêiner Docker
      - name: Run container test
        run: |
          docker run --rm -d -p 3000:3000 --name dummy-service-container dummy-service
          sleep 5 # Aguarde o serviço iniciar
          curl -f http://localhost:3000 || (docker logs dummy-service-container && exit 1)
          docker stop dummy-service-container
