name: Test Dockerfile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -f ./estoque/Dockerfile -t estoque ./estoque

    - name: Run Docker Container
      run: |
        docker run -d -p 3000:3000 --name estoque-container estoque
        sleep 5
        docker logs estoque-container
        curl -s http://localhost:3000 || exit 1
        docker stop estoque-container
        docker rm estoque-container

    - name: Clean up Docker images
      run: docker rmi estoque
