name: Test Shipping api

on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Navigate to the shipping service directory
      working-directory: ./shipping/shipping
      run: pwd

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}

    - name: Grant execute permission for gradlew
      working-directory: ./shipping/shipping
      run: chmod +x shipping/shipping/gradlew

    - name: Access shipping directory
      working-directory: ./shipping/shipping
      run: cd shipping/shipping

    - name: Build with Gradle
      working-directory: ./shipping/shipping
      run: ./gradlew build

    - name: Run Spring Boot application
      working-directory: ./shipping/shipping
      run: ./gradlew bootRun
      
    - name: Wait for server to start
      run: sleep 20 

    - name: Test health endpoint
      run: |
        curl -f http://localhost:8080/shipping/health | grep "OOk"
      shell: bash

    - name: Stop Spring Boot Application
      run: |
        kill $(lsof -t -i:8080)
